version: "3"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
  webproxy:
    external: false

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    #remove this port so the database isn't exposed to the internet
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/db_backup:/backup

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./nginx_conf:/etc/nginx/conf.d
    networks:
      - webproxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL={LETSENCRYPT_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    networks:
      - webproxy

  timingcloud:
    container_name: timingcloud
    build: ./services/timingcloud/.
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - IOTSTACK_UID=1000
      - IOTSTACK_GID=1000
      - DOCKER_HOST_IP=172.17.0.1
      - VIRTUAL_HOST={TIMINGSITE_HOST}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST={TIMINGSITE_HOST}
      - LETSENCRYPT_EMAIL={LETSENCRYPT_EMAIL}
    expose:
      - "5000"
    networks:
      - webproxy
      - default

  trackapi:
    container_name: trackapi
    build: ./services/trackapi/.
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - IOTSTACK_UID=1000
      - IOTSTACK_GID=1000
      - DOCKER_HOST_IP=172.17.0.1
      - VIRTUAL_HOST={TRACKAPI_HOST}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST={TRACKAPI_HOST}
      - LETSENCRYPT_EMAIL={LETSENCRYPT_EMAIL}
    expose:
      - "5000"
    networks:
      - webproxy
      - default


  # Copy and Uncomment below for an additional python container
  #
  #python:
  #  container_name: python
  #  build: ./services/python/.
  #  restart: unless-stopped
  #  environment:
  #  - TZ=Etc/UTC
  #  - IOTSTACK_UID=1000
  #  - IOTSTACK_GID=1000
  #  devices:
  #  - /dev/polaris:/dev/polaris
  #  x-ports:
  #  - "external:internal"
  #  volumes:
  #  - ./volumes/python/app:/usr/src/app
