"""empty message

Revision ID: 04c8f303d528
Revises: 
Create Date: 2024-07-16 21:28:07.563998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c8f303d528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('car_number', sa.String(length=128), nullable=False),
    sa.Column('cones', sa.Integer(), nullable=True),
    sa.Column('off_courses', sa.Integer(), nullable=True),
    sa.Column('dnfs', sa.Integer(), nullable=True),
    sa.Column('raw_time', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('adjusted_time', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_order_adjusted_time'), ['adjusted_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_car_number'), ['car_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_raw_time'), ['raw_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_team_name'), ['team_name'], unique=False)

    op.create_table('top_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('car_number', sa.String(length=128), nullable=False),
    sa.Column('cones', sa.Integer(), nullable=True),
    sa.Column('off_courses', sa.Integer(), nullable=True),
    sa.Column('dnfs', sa.Integer(), nullable=True),
    sa.Column('raw_time', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('adjusted_time', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'is_view': True}
    )
    with op.batch_alter_table('top_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_top_runs_adjusted_time'), ['adjusted_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_top_runs_car_number'), ['car_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_top_runs_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_top_runs_raw_time'), ['raw_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_top_runs_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_top_runs_team_name'), ['team_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_top_runs_team_name'))
        batch_op.drop_index(batch_op.f('ix_top_runs_tag'))
        batch_op.drop_index(batch_op.f('ix_top_runs_raw_time'))
        batch_op.drop_index(batch_op.f('ix_top_runs_location'))
        batch_op.drop_index(batch_op.f('ix_top_runs_car_number'))
        batch_op.drop_index(batch_op.f('ix_top_runs_adjusted_time'))

    op.drop_table('top_runs')
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_order_team_name'))
        batch_op.drop_index(batch_op.f('ix_run_order_tag'))
        batch_op.drop_index(batch_op.f('ix_run_order_raw_time'))
        batch_op.drop_index(batch_op.f('ix_run_order_location'))
        batch_op.drop_index(batch_op.f('ix_run_order_car_number'))
        batch_op.drop_index(batch_op.f('ix_run_order_adjusted_time'))

    op.drop_table('run_order')
    # ### end Alembic commands ###
