"""empty message

Revision ID: 2a596ca3264e
Revises: 4d83bd52e066
Create Date: 2024-08-01 22:03:58.580673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a596ca3264e'
down_revision = '4d83bd52e066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_reg', schema=None) as batch_op:
        batch_op.drop_index('ix_car_reg_tag')
        batch_op.create_index(batch_op.f('ix_car_reg_tag'), ['tag'], unique=True)

    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.drop_index('ix_run_order_tag')
        batch_op.create_index(batch_op.f('ix_run_order_tag'), ['tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_order_tag'))
        batch_op.create_index('ix_run_order_tag', ['tag'], unique=False)

    with op.batch_alter_table('car_reg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_reg_tag'))
        batch_op.create_index('ix_car_reg_tag', ['tag'], unique=False)

    # ### end Alembic commands ###
