"""empty message

Revision ID: 4d83bd52e066
Revises: 19f73bbbe5d0
Create Date: 2024-08-01 21:16:19.682176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d83bd52e066'
down_revision = '19f73bbbe5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.drop_index('ix_run_order_tag')
        batch_op.create_index(batch_op.f('ix_run_order_tag'), ['tag'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_order_tag'))
        batch_op.create_index('ix_run_order_tag', ['tag'], unique=False)

    # ### end Alembic commands ###
