"""empty message

Revision ID: 7d74216876b6
Revises: 
Create Date: 2024-08-01 23:15:23.819344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d74216876b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.drop_index('ix_run_order_location')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.create_index('ix_run_order_location', ['location'], unique=False)

    # ### end Alembic commands ###
