"""runs table

Revision ID: 94123ffd0593
Revises: 
Create Date: 2024-06-30 18:31:40.558405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94123ffd0593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('car_number', sa.String(length=128), nullable=False),
    sa.Column('cones', sa.String(length=128), nullable=False),
    sa.Column('off_courses', sa.String(length=128), nullable=False),
    sa.Column('raw_time', sa.String(length=128), nullable=False),
    sa.Column('adjusted_time', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_order_adjusted_time'), ['adjusted_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_car_number'), ['car_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_cones'), ['cones'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_off_courses'), ['off_courses'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_raw_time'), ['raw_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_order_team_name'), ['team_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_order_team_name'))
        batch_op.drop_index(batch_op.f('ix_run_order_tag'))
        batch_op.drop_index(batch_op.f('ix_run_order_raw_time'))
        batch_op.drop_index(batch_op.f('ix_run_order_off_courses'))
        batch_op.drop_index(batch_op.f('ix_run_order_location'))
        batch_op.drop_index(batch_op.f('ix_run_order_cones'))
        batch_op.drop_index(batch_op.f('ix_run_order_car_number'))
        batch_op.drop_index(batch_op.f('ix_run_order_adjusted_time'))

    op.drop_table('run_order')
    # ### end Alembic commands ###
